name: C Matrix Multiplication CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t matrix_multiplication .



      - name: Install Singularity
        run: |
          sudo apt-get update
          sudo apt-get install -y singularity-ce

      - name: Build Singularity Image
        run: singularity build matrix_multiplication.sif singularity.def

      - name: Run Test in Singularity
        run: singularity exec matrix_multiplication.sif /usr/local/bin/test_multiplication

      - name: Run Matrix Multiplication in Singularity
        run: singularity exec matrix_multiplication.sif /usr/local/bin/matrix_multiplication

